
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
public class Frame2 extends javax.swing.JFrame {

    /**
     * Creates new form Frame2
     */
    public Frame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tabel = new javax.swing.JTabbedPane();
        balok = new javax.swing.JPanel();
        Panjang = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Lebar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Tinggi = new javax.swing.JTextField();
        btnBalok = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kubus = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        SisiKubus = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnKubus = new javax.swing.JButton();
        bola = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Jarijari = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnBola = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel1.setText("Program Penghitung Volume Ruang Bangun");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 0, 300, 29);

        tabel.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N

        balok.setLayout(null);
        balok.add(Panjang);
        Panjang.setBounds(160, 30, 140, 30);

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel2.setText("Masukkan Panjang  :");
        balok.add(jLabel2);
        jLabel2.setBounds(10, 26, 140, 30);
        balok.add(Lebar);
        Lebar.setBounds(160, 70, 140, 30);

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel3.setText("Masukkan Lebar      :");
        balok.add(jLabel3);
        jLabel3.setBounds(10, 70, 140, 30);

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel4.setText("Masukkan Tinggi      :");
        balok.add(jLabel4);
        jLabel4.setBounds(10, 113, 140, 30);
        balok.add(Tinggi);
        Tinggi.setBounds(160, 110, 139, 30);

        btnBalok.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnBalok.setText("Hitung");
        btnBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBalokActionPerformed(evt);
            }
        });
        balok.add(btnBalok);
        btnBalok.setBounds(170, 180, 80, 30);

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel7.setText("cm");
        balok.add(jLabel7);
        jLabel7.setBounds(320, 110, 20, 20);

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel6.setText("cm");
        balok.add(jLabel6);
        jLabel6.setBounds(320, 70, 20, 20);

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel5.setText("cm");
        balok.add(jLabel5);
        jLabel5.setBounds(320, 30, 20, 20);

        tabel.addTab("Balok", balok);

        kubus.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel8.setText("Masukkan Panjang Sisi");
        kubus.add(jLabel8);
        jLabel8.setBounds(80, 20, 270, 30);

        SisiKubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SisiKubusActionPerformed(evt);
            }
        });
        kubus.add(SisiKubus);
        SisiKubus.setBounds(80, 60, 120, 40);

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel9.setText("cm");
        kubus.add(jLabel9);
        jLabel9.setBounds(210, 60, 40, 40);

        btnKubus.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnKubus.setText("Volume");
        btnKubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKubusActionPerformed(evt);
            }
        });
        kubus.add(btnKubus);
        btnKubus.setBounds(100, 130, 90, 31);

        tabel.addTab("Kubus", kubus);

        bola.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel10.setText("Masukkan Panjang Jari - Jari");
        bola.add(jLabel10);
        jLabel10.setBounds(90, 20, 220, 30);

        Jarijari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JarijariActionPerformed(evt);
            }
        });
        bola.add(Jarijari);
        Jarijari.setBounds(100, 60, 100, 40);

        jLabel11.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel11.setText("cm");
        bola.add(jLabel11);
        jLabel11.setBounds(210, 60, 40, 40);

        btnBola.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnBola.setText("Volume");
        btnBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBolaActionPerformed(evt);
            }
        });
        bola.add(btnBola);
        btnBola.setBounds(100, 120, 90, 30);

        tabel.addTab("Bola", bola);

        getContentPane().add(tabel);
        tabel.setBounds(0, 36, 425, 292);

        setBounds(0, 0, 439, 367);
    }// </editor-fold>//GEN-END:initComponents

    private void JarijariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JarijariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JarijariActionPerformed

    private void btnBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBolaActionPerformed
        // TODO add your handling code here:
        float jari;
        jari = Integer.parseInt(Jarijari.getText());
        float hasil1 = (float) (4/3*Math.PI*jari*jari);
        try {
            JOptionPane.showMessageDialog(null, "Luas Permukaan Bola Adalah :"+hasil1, "luas", 
                JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error"+e, "Gagal",
                JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnBolaActionPerformed

    private void SisiKubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SisiKubusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SisiKubusActionPerformed

    private void btnBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBalokActionPerformed
        // TODO add your handling code here:
        int panjang, lebar, tinggi;
        panjang=Integer.parseInt(Panjang.getText());
        lebar=Integer.parseInt(Lebar.getText());
        tinggi=Integer.parseInt(Tinggi.getText());
        int hasil=panjang*lebar*tinggi;
        try {
        JOptionPane.showMessageDialog(null,"Volume Balok Adalah :"+hasil,"luas",
                JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e){
        JOptionPane.showMessageDialog(null,"Error:"+e,"Gagal",
                JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnBalokActionPerformed

    private void btnKubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKubusActionPerformed
        // TODO add your handling code here:
        int sisi;
        sisi=Integer.parseInt(SisiKubus.getText());
        int hasil=sisi*sisi*sisi;
        
        try {
            JOptionPane.showMessageDialog(null, "Luas Permukaan Kubus adalah :"+hasil,"luas",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error"+e,"Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnKubusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Jarijari;
    private javax.swing.JTextField Lebar;
    private javax.swing.JTextField Panjang;
    private javax.swing.JTextField SisiKubus;
    private javax.swing.JTextField Tinggi;
    private javax.swing.JPanel balok;
    private javax.swing.JPanel bola;
    private javax.swing.JButton btnBalok;
    private javax.swing.JButton btnBola;
    private javax.swing.JButton btnKubus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel kubus;
    private javax.swing.JTabbedPane tabel;
    // End of variables declaration//GEN-END:variables
}
